//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_2T9kLMqRh"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "71i9ln5k4509dl98624uks6994"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1jfj5l1nbesd3lrrfcgcq6o3ncaurf53db42eiv5u5iob8urhpo4"
